<?php
/* 
   Template Name: Contact Form
   
   WARNING! DO NOT EDIT THIS FILE!

   BizzThemes theme framework is built with hooks and advanced conditional logic for
   containers, grids and widgets, which you may control from your theme template Builder. 
   Do not modify any theme files and only make changes through theme administration 
   or via 'custom' folder files.

*/

	bizz_html_index();